### ISSUE TITLE
can not select second subtitle

### ISSUE THREAD

**Issue by QGB** [mikesteele/dual-captions#127] opened 2020-02-05 10:20 UTC
https://www.youtube.com/watch?v=_ziP_4pouN8
![image](https://user-images.githubusercontent.com/8005654/73832998-3311c500-4844-11ea-810b-35b47665cb22.png)

**Comment by QGB** [comment] 2020-02-06 09:22
@mikesteele-drizly

**Comment by mikesteele** [comment] 2020-02-06 15:10
Hi! The issue is that the video you linked uses autogenerated subtitles, which aren't supported. I'm going to close this as there's a pre-existing issue for this #12

**Closed by mikesteele** 2020-02-06 15:10 UTC
